blank_issues_enabled: false
contact_links:
  - name: ðŸ—¨ probably start a discussion?
    about: Join the discord for chatting with the 2 other people that use Crack Natro!
    url: https://discord.gg/7wgKQvdfyq
